name: tintoreriadigital
description: "Proyecto TintoreriaDigital para la materia de Gestión de Proyectos de Software"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.3
  sqflite_common_ffi: ^2.3.4
  bitsdojo_window: ^0.1.6
  flutter_bloc: ^8.1.1
  path_provider: ^2.1.5
  syncfusion_flutter_datepicker: ^27.1.58
  roundcheckbox: ^2.0.5
  appflowy_board: ^0.1.2
  google_fonts: ^6.2.1
  provider: ^6.1.2
  table_calendar: ^3.1.2
  intl: ^0.19.0
  flutter_launcher_icons: ^0.14.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/logo.png

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/logo.png"
  min_sdk_android: 21
