name: tintoreriadigital
description: "Proyecto TintoreriaDigital para la materia de Gestión de Proyectos de Software"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.3
  sqflite_common_ffi: ^2.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
